=== ror-community/ror-records/json_schema/ror_schema_v2_1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://ror.org/schemas/v2.0/organization",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "admin": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "created": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "date": {
                            "type": "string",
                            "format": "date"
                        },
                        "schema_version": {
                            "type": "string",
                            "enum": [
                                "1.0",
                                "2.0",
                                "2.1"
                            ]
                        }
                    },
                    "required": [
                        "date",
                        "schema_version"
                    ]
                },
                "last_modified": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "date": {
                            "type": "string",
                            "format": "date"
                        },
                        "schema_version": {
                            "type": "string",
                            "enum": [
                                "1.0",
                                "2.0",
                                "2.1"
                            ]
                        }
                    },
                    "required": [
                        "date",
                        "schema_version"
                    ]
                }
            },
            "required": [
                "created",
                "last_modified"
            ]
        },
        "domains": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "string",
                "pattern": "^((?=[a-z0-9-]{1,63}\\.)[a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,63}$"
            }
        },
        "established": {
            "type": [
                "null",
                "number"
            ],
            "default": null
        },
        "external_ids": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "all": {
                        "type": "array",
                        "uniqueItems": true,
                        "default": [],
                        "items": {
                            "$ref": "#/$defs/non-empty-string"
                        }
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "fundref",
                            "grid",
                            "isni",
                            "wikidata"
                        ]
                    },
                    "preferred": {
                        "type": [
                            "string",
                            "null"
                        ]
                    }
                },
                "required": [
                    "all",
                    "type"
                ]
            }
        },
        "id": {
            "type": "string",
            "default": "https://ror.org/012xzy7a9",
            "pattern": "^https://ror.org/0[a-z|0-9]{8}$",
            "readOnly": true
        },
        "links": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "website",
                            "wikipedia"
                        ]
                    }
                },
                "required": [
                    "type",
                    "value"
                ]
            }
        },
        "locations": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "geonames_id",
                    "geonames_details"
                ],
                "properties": {
                    "geonames_id": {
                        "type": "integer"
                    },
                    "geonames_details": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "name": {
                                "$ref": "#/$defs/non-empty-string"
                            },
                            "lat": {
                                "type": [
                                    "number",
                                    "null"
                                ]
                            },
                            "lng": {
                                "type": [
                                    "number",
                                    "null"
                                ]
                            },
                            "continent_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "enum": [
                                    "AF",
                                    "AN",
                                    "AS",
                                    "EU",
                                    "NA",
                                    "OC",
                                    "SA",
                                    null
                                ]
                            },
                            "continent_name": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "enum": [
                                    "Africa",
                                    "Antarctica",
                                    "Asia",
                                    "Europe",
                                    "Oceania",
                                    "South America",
                                    "North America",
                                    null
                                ]
                            },
                            "country_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "pattern": "^[A-Z]{2}$",
                                "minLength": 2,
                                "maxLength": 2
                            },
                            "country_name": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "country_subdivision_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "pattern": "^[A-Z0-9]{1,3}$",
                                "minLength": 1,
                                "maxLength": 3
                            },
                            "country_subdivision_name": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            }
                        }
                    }
                }
            }
        },
        "names": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "value": {
                        "$ref": "#/$defs/non-empty-string"
                    },
                    "types": {
                        "type": "array",
                        "uniqueItems": true,
                        "default": [],
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "enum": [
                                "acronym",
                                "alias",
                                "label",
                                "ror_display"
                            ]
                        }
                    },
                    "lang": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "pattern": "^[a-z]{2}$",
                        "minLength": 2,
                        "maxLength": 2
                    }
                },
                "required": [
                    "types",
                    "value"
                ]
            }
        },
        "relationships": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": [
                            "related",
                            "parent",
                            "child",
                            "successor",
                            "predecessor"
                        ]
                    },
                    "id": {
                        "type": "string",
                        "pattern": "^https://ror.org/0[a-z|0-9]{8}$"
                    },
                    "label": {
                        "$ref": "#/$defs/non-empty-string"
                    }
                },
                "required": [
                    "id",
                    "label",
                    "type"
                ]
            }
        },
        "status": {
            "type": "string",
            "default": "active",
            "enum": [
                "active",
                "inactive",
                "withdrawn"
            ]
        },
        "types": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "default": [],
            "items": {
                "type": "string",
                "enum": [
                    "education",
                    "funder",
                    "healthcare",
                    "company",
                    "archive",
                    "nonprofit",
                    "government",
                    "facility",
                    "other"
                ]
            }
        }
    },
    "$defs": {
        "non-empty-string": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "admin",
        "id",
        "locations",
        "names",
        "status",
        "types"
    ]
}

=== ror-community/ror-records/v2.7/046p4xa68.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2026-05-05",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "pasteur.ci"
  ],
  "established": 1972,
  "external_ids": [
    {
      "all": [
        "grid.418523.9"
      ],
      "preferred": "grid.418523.9",
      "type": "grid"
    },
    {
      "all": [
        "0000 0004 0475 3667"
      ],
      "preferred": null,
      "type": "isni"
    }
  ],
  "id": "https://ror.org/046p4xa68",
  "links": [
    {
      "type": "website",
      "value": "https://pasteur.ci"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "AF",
        "continent_name": "Africa",
        "country_code": "CI",
        "country_name": "Ivory Coast",
        "country_subdivision_code": "AB",
        "country_subdivision_name": "Abidjan Autonomous District",
        "lat": 5.35444,
        "lng": -4.00167,
        "name": "Abidjan"
      },
      "geonames_id": 2293538
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "acronym"
      ],
      "value": "IPCI"
    },
    {
      "lang": "fr",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Institut Pasteur de Côte d'Ivoire"
    }
  ],
  "relationships": [
    {
      "label": "Institut Pasteur",
      "type": "related",
      "id": "https://ror.org/0495fxg12"
    },
    {
      "label": "Pasteur Network",
      "type": "related",
      "id": "https://ror.org/04cb2ne58"
    }
  ],
  "status": "active",
  "types": [
    "nonprofit"
  ]
}

=== ror-community/ror-records/v2.9/011ashp19.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "scu.edu.cn"
  ],
  "established": 1740,
  "external_ids": [
    {
      "all": [
        "501100004912"
      ],
      "preferred": null,
      "type": "fundref"
    },
    {
      "all": [
        "grid.13291.38"
      ],
      "preferred": "grid.13291.38",
      "type": "grid"
    },
    {
      "all": [
        "0000 0001 0807 1581"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q2281517"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/011ashp19",
  "links": [
    {
      "type": "website",
      "value": "https://scu.edu.cn"
    },
    {
      "type": "wikipedia",
      "value": "http://en.wikipedia.org/wiki/Sichuan_University"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "AS",
        "continent_name": "Asia",
        "country_code": "CN",
        "country_name": "China",
        "country_subdivision_code": "SC",
        "country_subdivision_name": "Sichuan",
        "lat": 30.66667,
        "lng": 104.06667,
        "name": "Chengdu"
      },
      "geonames_id": 1815286
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "acronym"
      ],
      "value": "SCU"
    },
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Sichuan University"
    },
    {
      "lang": null,
      "types": [
        "alias"
      ],
      "value": "Sìchuān Dàxué"
    },
    {
      "lang": "zh",
      "types": [
        "label"
      ],
      "value": "四川大学"
    }
  ],
  "relationships": [
    {
      "label": "West China Medical Center of Sichuan University",
      "type": "child",
      "id": "https://ror.org/040nggs60"
    },
    {
      "label": "State Key Laboratory of Biotherapy",
      "type": "child",
      "id": "https://ror.org/00x43yy22"
    },
    {
      "label": "State Key Laboratory of Oral Diseases",
      "type": "child",
      "id": "https://ror.org/00pvqk557"
    },
    {
      "label": "State Key Laboratory of Hydraulics and Mountain River Engineering",
      "type": "child",
      "id": "https://ror.org/02169wb20"
    },
    {
      "label": "State Key Laboratory of Polymer Materials Engineering",
      "type": "child",
      "id": "https://ror.org/02rbzhv36"
    },
    {
      "label": "West China Hospital of Sichuan University",
      "type": "related",
      "id": "https://ror.org/007mrxy13"
    },
    {
      "label": "West China Second University Hospital of Sichuan University",
      "type": "related",
      "id": "https://ror.org/00726et14"
    },
    {
      "label": "The First People's Hospital of Shuangliu District",
      "type": "related",
      "id": "https://ror.org/04cjrj888"
    }
  ],
  "status": "active",
  "types": [
    "education",
    "funder"
  ]
}

=== ror-community/ror-records/v1.73/04jmqe852.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2025-10-28",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "klinikum-fulda.de"
  ],
  "established": 1976,
  "external_ids": [
    {
      "all": [
        "grid.419818.d"
      ],
      "preferred": "grid.419818.d",
      "type": "grid"
    },
    {
      "all": [
        "0000 0001 0002 5193"
      ],
      "preferred": null,
      "type": "isni"
    }
  ],
  "id": "https://ror.org/04jmqe852",
  "links": [
    {
      "type": "website",
      "value": "https://klinikum-fulda.de"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "DE",
        "country_name": "Germany",
        "country_subdivision_code": "HE",
        "country_subdivision_name": "Hesse",
        "lat": 50.55162,
        "lng": 9.67518,
        "name": "Fulda"
      },
      "geonames_id": 2923822
    }
  ],
  "names": [
    {
      "lang": "de",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Klinikum Fulda"
    }
  ],
  "relationships": [
    {
      "label": "Philipps University of Marburg",
      "type": "related",
      "id": "https://ror.org/01rdrb571"
    }
  ],
  "status": "active",
  "types": [
    "healthcare"
  ]
}

=== ror-community/ror-records/v2.9/0335r7f92.json
{
  "admin": {
    "created": {
      "date": "2026-06-14",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "visionclub.ca"
  ],
  "established": 2003,
  "external_ids": [
    {
      "all": [
        "100008498"
      ],
      "preferred": "100008498",
      "type": "fundref"
    }
  ],
  "id": "https://ror.org/0335r7f92",
  "links": [
    {
      "type": "website",
      "value": "https://www.visionclub.ca"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "NA",
        "continent_name": "North America",
        "country_code": "CA",
        "country_name": "Canada",
        "country_subdivision_code": "ON",
        "country_subdivision_name": "Ontario",
        "lat": 43.80011,
        "lng": -79.48291,
        "name": "Concord"
      },
      "geonames_id": 5926526
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Brandan's Eye Research Foundation"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "funder",
    "nonprofit"
  ]
}

=== ror-community/ror-records/v2.9/00tqf7777.json
{
  "admin": {
    "created": {
      "date": "2026-06-14",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "fondationpierredeniker.org"
  ],
  "established": 2007,
  "external_ids": [
    {
      "all": [
        "501100008312"
      ],
      "preferred": "501100008312",
      "type": "fundref"
    }
  ],
  "id": "https://ror.org/00tqf7777",
  "links": [
    {
      "type": "website",
      "value": "https://www.fondationpierredeniker.org"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "FR",
        "country_name": "France",
        "country_subdivision_code": "IDF",
        "country_subdivision_name": "Île-de-France",
        "lat": 48.85341,
        "lng": 2.3488,
        "name": "Paris"
      },
      "geonames_id": 2988507
    }
  ],
  "names": [
    {
      "lang": "fr",
      "types": [
        "alias"
      ],
      "value": "Fondation Pierre Deniker"
    },
    {
      "lang": "fr",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Fondation Pierre Deniker pour la Recherche et la Prévention en Santé Mentale"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Pierre Deniker Foundation"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "funder",
    "nonprofit"
  ]
}

=== ror-community/ror-records/v2.8/01tspta37.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2026-06-02",
      "schema_version": "2.1"
    }
  },
  "domains": [],
  "established": 1992,
  "external_ids": [
    {
      "all": [
        "501100013224"
      ],
      "preferred": "501100013224",
      "type": "fundref"
    },
    {
      "all": [
        "grid.419239.4"
      ],
      "preferred": "grid.419239.4",
      "type": "grid"
    },
    {
      "all": [
        "0000 0000 8583 7301"
      ],
      "preferred": null,
      "type": "isni"
    }
  ],
  "id": "https://ror.org/01tspta37",
  "links": [
    {
      "type": "website",
      "value": "http://www.ipfdd.de/en/home/our-mission/"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "DE",
        "country_name": "Germany",
        "country_subdivision_code": "SN",
        "country_subdivision_name": "Saxony",
        "lat": 51.05089,
        "lng": 13.73832,
        "name": "Dresden"
      },
      "geonames_id": 2935022
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "acronym"
      ],
      "value": "IPF"
    },
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Leibniz Institute of Polymer Research"
    },
    {
      "lang": "de",
      "types": [
        "label"
      ],
      "value": "Leibniz-Institut für Polymerforschung Dresden"
    }
  ],
  "relationships": [
    {
      "label": "Leibniz Association",
      "type": "parent",
      "id": "https://ror.org/01n6r0e97"
    },
    {
      "label": "Physics of Life",
      "type": "related",
      "id": "https://ror.org/029yt9178"
    },
    {
      "label": "Center for Regenerative Therapies Dresden",
      "type": "related",
      "id": "https://ror.org/00490nx58"
    }
  ],
  "status": "active",
  "types": [
    "facility",
    "funder"
  ]
}

=== ror-community/ror-records/v2.9/04kvwhe72.json
{
  "admin": {
    "created": {
      "date": "2026-06-14",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "ilp.upmc.fr"
  ],
  "established": 2011,
  "external_ids": [
    {
      "all": [
        "501100014224"
      ],
      "preferred": "501100014224",
      "type": "fundref"
    }
  ],
  "id": "https://ror.org/04kvwhe72",
  "links": [
    {
      "type": "website",
      "value": "http://ilp.upmc.fr"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "FR",
        "country_name": "France",
        "country_subdivision_code": "IDF",
        "country_subdivision_name": "Île-de-France",
        "lat": 48.85341,
        "lng": 2.3488,
        "name": "Paris"
      },
      "geonames_id": 2988507
    }
  ],
  "names": [
    {
      "lang": "fr",
      "types": [
        "acronym"
      ],
      "value": "ILP"
    },
    {
      "lang": "fr",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Institut Lagrange de Paris"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "The Lagrange Institute, Paris"
    }
  ],
  "relationships": [],
  "status": "inactive",
  "types": [
    "facility",
    "funder"
  ]
}

=== ror-community/ror-records/ror_releases/v1.51/03zhyf578.json
{
  "admin": {
    "created": {
      "date": "2024-08-19",
      "schema_version": "2.0"
    },
    "last_modified": {
      "date": "2024-08-21",
      "schema_version": "2.0"
    }
  },
  "domains": [],
  "established": null,
  "external_ids": [
    {
      "all": [
        "Q51782558"
      ],
      "preferred": "Q51782558",
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/03zhyf578",
  "links": [
    {
      "type": "website",
      "value": "https://ur-geco.cirad.fr"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "country_code": "FR",
        "country_name": "France",
        "lat": 48.85341,
        "lng": 2.3488,
        "name": "Paris"
      },
      "geonames_id": 2988507
    }
  ],
  "names": [
    {
      "lang": "fr",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Fonctionnement écologique et gestion durable des agrosystèmes bananiers et ananas"
    },
    {
      "lang": "en",
      "types": [
        "label"
      ],
      "value": "Functioning and Sustainable Management of Banana and Pineapple"
    },
    {
      "lang": "fr",
      "types": [
        "alias"
      ],
      "value": "UPR Geco"
    },
    {
      "lang": "fr",
      "types": [
        "alias"
      ],
      "value": "Unité de recherche Geco"
    }
  ],
  "relationships": [
    {
      "label": "Centre de Coopération Internationale en Recherche Agronomique pour le Développement",
      "type": "parent",
      "id": "https://ror.org/05kpkpg04"
    }
  ],
  "status": "active",
  "types": [
    "facility"
  ]
}
