=== ror-community/ror-records/json_schema/ror_schema_v2_1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://ror.org/schemas/v2.0/organization",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "admin": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "created": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "date": {
                            "type": "string",
                            "format": "date"
                        },
                        "schema_version": {
                            "type": "string",
                            "enum": [
                                "1.0",
                                "2.0",
                                "2.1"
                            ]
                        }
                    },
                    "required": [
                        "date",
                        "schema_version"
                    ]
                },
                "last_modified": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "date": {
                            "type": "string",
                            "format": "date"
                        },
                        "schema_version": {
                            "type": "string",
                            "enum": [
                                "1.0",
                                "2.0",
                                "2.1"
                            ]
                        }
                    },
                    "required": [
                        "date",
                        "schema_version"
                    ]
                }
            },
            "required": [
                "created",
                "last_modified"
            ]
        },
        "domains": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "string",
                "pattern": "^((?=[a-z0-9-]{1,63}\\.)[a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,63}$"
            }
        },
        "established": {
            "type": [
                "null",
                "number"
            ],
            "default": null
        },
        "external_ids": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "all": {
                        "type": "array",
                        "uniqueItems": true,
                        "default": [],
                        "items": {
                            "$ref": "#/$defs/non-empty-string"
                        }
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "fundref",
                            "grid",
                            "isni",
                            "wikidata"
                        ]
                    },
                    "preferred": {
                        "type": [
                            "string",
                            "null"
                        ]
                    }
                },
                "required": [
                    "all",
                    "type"
                ]
            }
        },
        "id": {
            "type": "string",
            "default": "https://ror.org/012xzy7a9",
            "pattern": "^https://ror.org/0[a-z|0-9]{8}$",
            "readOnly": true
        },
        "links": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "website",
                            "wikipedia"
                        ]
                    }
                },
                "required": [
                    "type",
                    "value"
                ]
            }
        },
        "locations": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "geonames_id",
                    "geonames_details"
                ],
                "properties": {
                    "geonames_id": {
                        "type": "integer"
                    },
                    "geonames_details": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "name": {
                                "$ref": "#/$defs/non-empty-string"
                            },
                            "lat": {
                                "type": [
                                    "number",
                                    "null"
                                ]
                            },
                            "lng": {
                                "type": [
                                    "number",
                                    "null"
                                ]
                            },
                            "continent_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "enum": [
                                    "AF",
                                    "AN",
                                    "AS",
                                    "EU",
                                    "NA",
                                    "OC",
                                    "SA",
                                    null
                                ]
                            },
                            "continent_name": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "enum": [
                                    "Africa",
                                    "Antarctica",
                                    "Asia",
                                    "Europe",
                                    "Oceania",
                                    "South America",
                                    "North America",
                                    null
                                ]
                            },
                            "country_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "pattern": "^[A-Z]{2}$",
                                "minLength": 2,
                                "maxLength": 2
                            },
                            "country_name": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "country_subdivision_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "pattern": "^[A-Z0-9]{1,3}$",
                                "minLength": 1,
                                "maxLength": 3
                            },
                            "country_subdivision_name": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            }
                        }
                    }
                }
            }
        },
        "names": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "value": {
                        "$ref": "#/$defs/non-empty-string"
                    },
                    "types": {
                        "type": "array",
                        "uniqueItems": true,
                        "default": [],
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "enum": [
                                "acronym",
                                "alias",
                                "label",
                                "ror_display"
                            ]
                        }
                    },
                    "lang": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "pattern": "^[a-z]{2}$",
                        "minLength": 2,
                        "maxLength": 2
                    }
                },
                "required": [
                    "types",
                    "value"
                ]
            }
        },
        "relationships": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": [
                            "related",
                            "parent",
                            "child",
                            "successor",
                            "predecessor"
                        ]
                    },
                    "id": {
                        "type": "string",
                        "pattern": "^https://ror.org/0[a-z|0-9]{8}$"
                    },
                    "label": {
                        "$ref": "#/$defs/non-empty-string"
                    }
                },
                "required": [
                    "id",
                    "label",
                    "type"
                ]
            }
        },
        "status": {
            "type": "string",
            "default": "active",
            "enum": [
                "active",
                "inactive",
                "withdrawn"
            ]
        },
        "types": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "default": [],
            "items": {
                "type": "string",
                "enum": [
                    "education",
                    "funder",
                    "healthcare",
                    "company",
                    "archive",
                    "nonprofit",
                    "government",
                    "facility",
                    "other"
                ]
            }
        }
    },
    "$defs": {
        "non-empty-string": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "admin",
        "id",
        "locations",
        "names",
        "status",
        "types"
    ]
}

=== ror-community/ror-records/v2.7/04hxxzz17.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2026-05-05",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "heanet.ie"
  ],
  "established": 1983,
  "external_ids": [
    {
      "all": [
        "grid.435211.0"
      ],
      "preferred": "grid.435211.0",
      "type": "grid"
    },
    {
      "all": [
        "0000 0004 0518 964X"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q5629412"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/04hxxzz17",
  "links": [
    {
      "type": "website",
      "value": "https://www.heanet.ie"
    },
    {
      "type": "wikipedia",
      "value": "https://en.wikipedia.org/wiki/HEAnet"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "IE",
        "country_name": "Ireland",
        "country_subdivision_code": "L",
        "country_subdivision_name": "Leinster",
        "lat": 53.33306,
        "lng": -6.24889,
        "name": "Dublin"
      },
      "geonames_id": 2964574
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "ror_display",
        "label"
      ],
      "value": "HEAnet"
    }
  ],
  "relationships": [
    {
      "label": "Asiera (Ireland)",
      "type": "successor",
      "id": "https://ror.org/05p8mqd12"
    }
  ],
  "status": "inactive",
  "types": [
    "other"
  ]
}

=== ror-community/ror-records/v2.7/026b73g96.json
{
  "admin": {
    "created": {
      "date": "2026-05-04",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-05-05",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "ncvb.kz"
  ],
  "established": 1977,
  "external_ids": [
    {
      "all": [
        "0000 0004 0387 7756"
      ],
      "preferred": "0000 0004 0387 7756",
      "type": "isni"
    }
  ],
  "id": "https://ror.org/026b73g96",
  "links": [
    {
      "type": "website",
      "value": "https://ncvb.kz"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "AS",
        "continent_name": "Asia",
        "country_code": "KZ",
        "country_name": "Kazakhstan",
        "country_subdivision_code": "75",
        "country_subdivision_name": "Almaty",
        "lat": 43.25249,
        "lng": 76.9115,
        "name": "Almaty"
      },
      "geonames_id": 1526384
    }
  ],
  "names": [
    {
      "lang": "kk",
      "types": [
        "label"
      ],
      "value": "\"Кардиология және ішкі ауруларғылыми-зерттеу институты\" АҚ"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "JSC \"Research Institute of Cardiology and Internal Diseases\""
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "JSC Research Institute of Cardiology and Internal Diseases"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Research Institute of Cardiology and Internal Diseases"
    },
    {
      "lang": "ru",
      "types": [
        "alias"
      ],
      "value": "АО \"НИИ КВБ\""
    },
    {
      "lang": "ru",
      "types": [
        "label"
      ],
      "value": "АО «Научно-исследовательский институт кардиологии и внутренних болезней»"
    },
    {
      "lang": "ru",
      "types": [
        "alias"
      ],
      "value": "АО НИИ кардиологии и внутренних болезней"
    },
    {
      "lang": "kk",
      "types": [
        "alias"
      ],
      "value": "Кардиология және ішкі аурулар ғылыми-зерттеу институты"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "facility",
    "healthcare"
  ]
}

=== ror-community/ror-records/releases/v1.51/01xc2fv34.json
{
  "admin": {
    "created": {
      "date": "2024-08-19",
      "schema_version": "2.0"
    },
    "last_modified": {
      "date": "2024-08-21",
      "schema_version": "2.0"
    }
  },
  "domains": [
    "mosaicco.com"
  ],
  "established": null,
  "external_ids": [
    {
      "all": [
        "100011350"
      ],
      "preferred": "100011350",
      "type": "fundref"
    },
    {
      "all": [
        "Q7752327"
      ],
      "preferred": "Q7752327",
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/01xc2fv34",
  "links": [
    {
      "type": "website",
      "value": "https://www.mosaicco.com"
    },
    {
      "type": "wikipedia",
      "value": "https://en.wikipedia.org/wiki/The_Mosaic_Company"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "country_code": "US",
        "country_name": "United States",
        "lat": 27.94752,
        "lng": -82.45843,
        "name": "Tampa"
      },
      "geonames_id": 4174757
    }
  ],
  "names": [
    {
      "lang": "de",
      "types": [
        "alias"
      ],
      "value": "Mosaic Co"
    },
    {
      "lang": "en",
      "types": [
        "label"
      ],
      "value": "Mosaic Company"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Mosaic Company (United States)"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "The Mosaic Co"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "company",
    "funder"
  ]
}

=== ror-community/ror-records/v1.73/02snehe53.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2025-10-28",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "kiryu-u.ac.jp"
  ],
  "established": 1901,
  "external_ids": [
    {
      "all": [
        "grid.448781.6"
      ],
      "preferred": "grid.448781.6",
      "type": "grid"
    },
    {
      "all": [
        "0000 0004 0638 7154"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q6416339"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/02snehe53",
  "links": [
    {
      "type": "website",
      "value": "https://www.kiryu-u.ac.jp"
    },
    {
      "type": "wikipedia",
      "value": "https://en.wikipedia.org/wiki/Kiryu_University"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "AS",
        "continent_name": "Asia",
        "country_code": "JP",
        "country_name": "Japan",
        "country_subdivision_code": "10",
        "country_subdivision_name": "Gunma",
        "lat": 36.44492,
        "lng": 139.28448,
        "name": "Midori"
      },
      "geonames_id": 6822155
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Kiryu University"
    },
    {
      "lang": "ja",
      "types": [
        "label"
      ],
      "value": "桐生大学"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "education"
  ]
}

=== ror-community/ror-records/v2.8/00em1jy13.json
{
  "admin": {
    "created": {
      "date": "2026-05-30",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-02",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "bgi-nutri.com"
  ],
  "established": null,
  "external_ids": [],
  "id": "https://ror.org/00em1jy13",
  "links": [
    {
      "type": "website",
      "value": "https://www.bgi-nutri.com"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "AS",
        "continent_name": "Asia",
        "country_code": "CN",
        "country_name": "China",
        "country_subdivision_code": "GD",
        "country_subdivision_name": "Guangdong",
        "lat": 22.54554,
        "lng": 114.0683,
        "name": "Shenzhen"
      },
      "geonames_id": 1795565
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "alias"
      ],
      "value": "BGI Nutri"
    },
    {
      "lang": null,
      "types": [
        "alias"
      ],
      "value": "BGI Precision Nutrition (Shenzhen) Technology Co., Limited"
    },
    {
      "lang": null,
      "types": [
        "label"
      ],
      "value": "BGI Precision Nutrition (Shenzhen) Technology Co., Ltd."
    },
    {
      "lang": null,
      "types": [
        "label",
        "ror_display"
      ],
      "value": "BGI Precision Nutrition (Shenzhen) Technology Co., Ltd. (China)"
    },
    {
      "lang": null,
      "types": [
        "label"
      ],
      "value": "华大精准营养（深圳）科技有限公司"
    },
    {
      "lang": null,
      "types": [
        "label"
      ],
      "value": "华大精准营养（深圳）科技有限公司 (China)"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "company"
  ]
}

=== ror-community/ror-records/v2.9/04shvqp53.json
{
  "admin": {
    "created": {
      "date": "2026-06-14",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "vnmt.org"
  ],
  "established": 2010,
  "external_ids": [
    {
      "all": [
        "501100017573"
      ],
      "preferred": "501100017573",
      "type": "fundref"
    }
  ],
  "id": "https://ror.org/04shvqp53",
  "links": [
    {
      "type": "website",
      "value": "https://www.vnmt.org"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "OC",
        "continent_name": "Oceania",
        "country_code": "AU",
        "country_name": "Australia",
        "country_subdivision_code": "VIC",
        "country_subdivision_name": "Victoria",
        "lat": -37.53078,
        "lng": 143.82838,
        "name": "Wendouree"
      },
      "geonames_id": 2144139
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "acronym"
      ],
      "value": "NBVLL"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Nurses Board of Victoria Legacy Limited"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Nurses Board of Victoria Legacy Ltd"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Nurses Board of Victoria Legacy Trust"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "The Nurses Board of Victoria Legacy Trust"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "The Victorian Nurses and Midwives Trust"
    },
    {
      "lang": "en",
      "types": [
        "acronym"
      ],
      "value": "VNMT"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "funder",
    "nonprofit"
  ]
}

=== ror-community/ror-records/ror_releases/v1.51/03wmf1y16.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2024-08-21",
      "schema_version": "2.0"
    }
  },
  "domains": [],
  "established": 1876,
  "external_ids": [
    {
      "all": [
        "100016193",
        "100014450"
      ],
      "preferred": "100014450",
      "type": "fundref"
    },
    {
      "all": [
        "grid.430503.1"
      ],
      "preferred": "grid.430503.1",
      "type": "grid"
    },
    {
      "all": [
        "0000 0001 0703 675X"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q4770537"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/03wmf1y16",
  "links": [
    {
      "type": "website",
      "value": "https://www.cuanschutz.edu/"
    },
    {
      "type": "wikipedia",
      "value": "http://en.wikipedia.org/wiki/Anschutz_Medical_Campus"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "country_code": "US",
        "country_name": "United States",
        "lat": 39.72943,
        "lng": -104.83192,
        "name": "Aurora"
      },
      "geonames_id": 5412347
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "CU Anschutz Medical Campus"
    },
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "University of Colorado Anschutz Medical Campus"
    }
  ],
  "relationships": [
    {
      "label": "University of Colorado Cancer Center",
      "type": "related",
      "id": "https://ror.org/04cqn7d42"
    },
    {
      "label": "University of Colorado Hospital",
      "type": "related",
      "id": "https://ror.org/006jjmw19"
    },
    {
      "label": "Rocky Mountain Advanced Computing Consortium",
      "type": "related",
      "id": "https://ror.org/019q0z051"
    }
  ],
  "status": "active",
  "types": [
    "education",
    "funder"
  ]
}

=== ror-community/ror-records/releases/v1.51/008khdx92.json
{
  "admin": {
    "created": {
      "date": "2024-08-19",
      "schema_version": "2.0"
    },
    "last_modified": {
      "date": "2024-08-21",
      "schema_version": "2.0"
    }
  },
  "domains": [
    "comerica.com"
  ],
  "established": null,
  "external_ids": [
    {
      "all": [
        "0000 0004 0438 2739"
      ],
      "preferred": "0000 0004 0438 2739",
      "type": "isni"
    },
    {
      "all": [
        "Q1114148"
      ],
      "preferred": "Q1114148",
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/008khdx92",
  "links": [
    {
      "type": "website",
      "value": "https://www.comerica.com"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "country_code": "US",
        "country_name": "United States",
        "lat": 32.78306,
        "lng": -96.80667,
        "name": "Dallas"
      },
      "geonames_id": 4684888
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "label"
      ],
      "value": "Comerica"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Comerica (United States)"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Comerica Bank"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Comerica Inc"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Comerica Incorporated"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "company"
  ]
}
