=== ror-community/ror-records/json_schema/ror_schema_v2_1.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://ror.org/schemas/v2.0/organization",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "admin": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "created": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "date": {
                            "type": "string",
                            "format": "date"
                        },
                        "schema_version": {
                            "type": "string",
                            "enum": [
                                "1.0",
                                "2.0",
                                "2.1"
                            ]
                        }
                    },
                    "required": [
                        "date",
                        "schema_version"
                    ]
                },
                "last_modified": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "date": {
                            "type": "string",
                            "format": "date"
                        },
                        "schema_version": {
                            "type": "string",
                            "enum": [
                                "1.0",
                                "2.0",
                                "2.1"
                            ]
                        }
                    },
                    "required": [
                        "date",
                        "schema_version"
                    ]
                }
            },
            "required": [
                "created",
                "last_modified"
            ]
        },
        "domains": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "string",
                "pattern": "^((?=[a-z0-9-]{1,63}\\.)[a-z0-9]+(-[a-z0-9]+)*\\.)+[a-z]{2,63}$"
            }
        },
        "established": {
            "type": [
                "null",
                "number"
            ],
            "default": null
        },
        "external_ids": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "all": {
                        "type": "array",
                        "uniqueItems": true,
                        "default": [],
                        "items": {
                            "$ref": "#/$defs/non-empty-string"
                        }
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "fundref",
                            "grid",
                            "isni",
                            "wikidata"
                        ]
                    },
                    "preferred": {
                        "type": [
                            "string",
                            "null"
                        ]
                    }
                },
                "required": [
                    "all",
                    "type"
                ]
            }
        },
        "id": {
            "type": "string",
            "default": "https://ror.org/012xzy7a9",
            "pattern": "^https://ror.org/0[a-z|0-9]{8}$",
            "readOnly": true
        },
        "links": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "website",
                            "wikipedia"
                        ]
                    }
                },
                "required": [
                    "type",
                    "value"
                ]
            }
        },
        "locations": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                    "geonames_id",
                    "geonames_details"
                ],
                "properties": {
                    "geonames_id": {
                        "type": "integer"
                    },
                    "geonames_details": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": [
                            "name"
                        ],
                        "properties": {
                            "name": {
                                "$ref": "#/$defs/non-empty-string"
                            },
                            "lat": {
                                "type": [
                                    "number",
                                    "null"
                                ]
                            },
                            "lng": {
                                "type": [
                                    "number",
                                    "null"
                                ]
                            },
                            "continent_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "enum": [
                                    "AF",
                                    "AN",
                                    "AS",
                                    "EU",
                                    "NA",
                                    "OC",
                                    "SA",
                                    null
                                ]
                            },
                            "continent_name": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "enum": [
                                    "Africa",
                                    "Antarctica",
                                    "Asia",
                                    "Europe",
                                    "Oceania",
                                    "South America",
                                    "North America",
                                    null
                                ]
                            },
                            "country_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "pattern": "^[A-Z]{2}$",
                                "minLength": 2,
                                "maxLength": 2
                            },
                            "country_name": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "country_subdivision_code": {
                                "type": [
                                    "string",
                                    "null"
                                ],
                                "pattern": "^[A-Z0-9]{1,3}$",
                                "minLength": 1,
                                "maxLength": 3
                            },
                            "country_subdivision_name": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            }
                        }
                    }
                }
            }
        },
        "names": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "minItems": 1,
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "value": {
                        "$ref": "#/$defs/non-empty-string"
                    },
                    "types": {
                        "type": "array",
                        "uniqueItems": true,
                        "default": [],
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "enum": [
                                "acronym",
                                "alias",
                                "label",
                                "ror_display"
                            ]
                        }
                    },
                    "lang": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "pattern": "^[a-z]{2}$",
                        "minLength": 2,
                        "maxLength": 2
                    }
                },
                "required": [
                    "types",
                    "value"
                ]
            }
        },
        "relationships": {
            "type": "array",
            "uniqueItems": true,
            "default": [],
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "type": {
                        "type": "string",
                        "enum": [
                            "related",
                            "parent",
                            "child",
                            "successor",
                            "predecessor"
                        ]
                    },
                    "id": {
                        "type": "string",
                        "pattern": "^https://ror.org/0[a-z|0-9]{8}$"
                    },
                    "label": {
                        "$ref": "#/$defs/non-empty-string"
                    }
                },
                "required": [
                    "id",
                    "label",
                    "type"
                ]
            }
        },
        "status": {
            "type": "string",
            "default": "active",
            "enum": [
                "active",
                "inactive",
                "withdrawn"
            ]
        },
        "types": {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "default": [],
            "items": {
                "type": "string",
                "enum": [
                    "education",
                    "funder",
                    "healthcare",
                    "company",
                    "archive",
                    "nonprofit",
                    "government",
                    "facility",
                    "other"
                ]
            }
        }
    },
    "$defs": {
        "non-empty-string": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "admin",
        "id",
        "locations",
        "names",
        "status",
        "types"
    ]
}

=== ror-community/ror-records/v1.73/01y414495.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2025-10-28",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "psbedu.paris"
  ],
  "established": 1974,
  "external_ids": [
    {
      "all": [
        "grid.469042.d"
      ],
      "preferred": "grid.469042.d",
      "type": "grid"
    },
    {
      "all": [
        "0000 0004 1781 6786"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q3578449"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/01y414495",
  "links": [
    {
      "type": "website",
      "value": "https://www.psbedu.paris/fr"
    },
    {
      "type": "wikipedia",
      "value": "https://en.wikipedia.org/wiki/Paris_School_of_Business"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "FR",
        "country_name": "France",
        "country_subdivision_code": "IDF",
        "country_subdivision_name": "ÃŽle-de-France",
        "lat": 48.85341,
        "lng": 2.3488,
        "name": "Paris"
      },
      "geonames_id": 2988507
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "ESG Management School"
    },
    {
      "lang": null,
      "types": [
        "acronym"
      ],
      "value": "PSB"
    },
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Paris School of Business"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "education"
  ]
}

=== ror-community/ror-records/v2.8/02w6v9q55.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2026-06-02",
      "schema_version": "2.1"
    }
  },
  "domains": [],
  "established": 1922,
  "external_ids": [
    {
      "all": [
        "grid.445465.2"
      ],
      "preferred": "grid.445465.2",
      "type": "grid"
    },
    {
      "all": [
        "0000 0004 0621 398X"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q9143067"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/02w6v9q55",
  "links": [
    {
      "type": "website",
      "value": "http://www.aps.edu.pl/"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "PL",
        "country_name": "Poland",
        "country_subdivision_code": "14",
        "country_subdivision_name": "Mazovia",
        "lat": 52.22977,
        "lng": 21.01178,
        "name": "Warsaw"
      },
      "geonames_id": 756135
    }
  ],
  "names": [
    {
      "lang": "pl",
      "types": [
        "label"
      ],
      "value": "Akademia Pedagogiki Specjalnej im. Marii Grzegorzewskiej"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Maria Grzegorzewska Academy of Special Education"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Maria Grzegorzewska University"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "The Maria Grzegorzewska University"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "education"
  ]
}

=== ror-community/ror-records/ror_releases/v1.50/01vhsdf43.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2024-07-29",
      "schema_version": "2.0"
    }
  },
  "domains": [],
  "established": 1801,
  "external_ids": [
    {
      "all": [
        "grid.446390.c"
      ],
      "preferred": "grid.446390.c",
      "type": "grid"
    },
    {
      "all": [
        "Q524435"
      ],
      "preferred": "Q524435",
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/01vhsdf43",
  "links": [
    {
      "type": "website",
      "value": "http://brooklynnavyyard.org/"
    },
    {
      "type": "wikipedia",
      "value": "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "country_code": "US",
        "country_name": "United States",
        "lat": 40.6501,
        "lng": -73.94958,
        "name": "Brooklyn"
      },
      "geonames_id": 5110302
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "acronym"
      ],
      "value": "BNY"
    },
    {
      "lang": null,
      "types": [
        "acronym"
      ],
      "value": "BNYDC"
    },
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Brooklyn Navy Yard"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Brooklyn Navy Yard Development Corporation"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "nonprofit"
  ]
}

=== ror-community/ror-records/v2.9/05t0gg285.json
{
  "admin": {
    "created": {
      "date": "2026-06-14",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "eahad.org"
  ],
  "established": 2007,
  "external_ids": [
    {
      "all": [
        "501100011926"
      ],
      "preferred": "501100011926",
      "type": "fundref"
    }
  ],
  "id": "https://ror.org/05t0gg285",
  "links": [
    {
      "type": "website",
      "value": "https://www.eahad.org"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "BE",
        "country_name": "Belgium",
        "country_subdivision_code": "BRU",
        "country_subdivision_name": "Brussels Capital",
        "lat": 50.85045,
        "lng": 4.34878,
        "name": "Brussels"
      },
      "geonames_id": 2800866
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "acronym"
      ],
      "value": "EAHAD"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "European Association for Haemophilia and Allied Disorders"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "funder",
    "nonprofit"
  ]
}

=== ror-community/ror-records/v2.9/012b6gm34.json
{
  "admin": {
    "created": {
      "date": "2026-06-14",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "grapesfromcalifornia.com"
  ],
  "established": 1967,
  "external_ids": [
    {
      "all": [
        "100015925"
      ],
      "preferred": "100015925",
      "type": "fundref"
    }
  ],
  "id": "https://ror.org/012b6gm34",
  "links": [
    {
      "type": "website",
      "value": "https://www.grapesfromcalifornia.com"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "NA",
        "continent_name": "North America",
        "country_code": "US",
        "country_name": "United States",
        "country_subdivision_code": "CA",
        "country_subdivision_name": "California",
        "lat": 36.74773,
        "lng": -119.77237,
        "name": "Fresno"
      },
      "geonames_id": 5350937
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "California Table Grape Commission"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "California Table Grapes"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Grapes from California"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "funder",
    "nonprofit"
  ]
}

=== ror-community/ror-records/v2.9/0462jy631.json
{
  "admin": {
    "created": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [
    "aimos.community"
  ],
  "established": 2019,
  "external_ids": [],
  "id": "https://ror.org/0462jy631",
  "links": [
    {
      "type": "website",
      "value": "https://aimos.community"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "OC",
        "continent_name": "Oceania",
        "country_code": "AU",
        "country_name": "Australia",
        "country_subdivision_code": "VIC",
        "country_subdivision_name": "Victoria",
        "lat": -37.814,
        "lng": 144.96332,
        "name": "Melbourne"
      },
      "geonames_id": 2158177
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "acronym"
      ],
      "value": "AIMOS"
    },
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Association for Interdisciplinary Meta-Research and Open Science"
    },
    {
      "lang": "en",
      "types": [
        "label",
        "ror_display"
      ],
      "value": "Association for Interdisciplinary Metaresearch and Open Science"
    }
  ],
  "relationships": [],
  "status": "active",
  "types": [
    "nonprofit"
  ]
}

=== ror-community/ror-records/v1.73/030d91z44.json
{
  "admin": {
    "created": {
      "date": "2018-11-14",
      "schema_version": "1.0"
    },
    "last_modified": {
      "date": "2025-10-28",
      "schema_version": "2.1"
    }
  },
  "domains": [],
  "established": 1870,
  "external_ids": [
    {
      "all": [
        "grid.416187.d"
      ],
      "preferred": "grid.416187.d",
      "type": "grid"
    },
    {
      "all": [
        "0000 0004 0400 8130"
      ],
      "preferred": null,
      "type": "isni"
    },
    {
      "all": [
        "Q7374640"
      ],
      "preferred": null,
      "type": "wikidata"
    }
  ],
  "id": "https://ror.org/030d91z44",
  "links": [
    {
      "type": "website",
      "value": "http://www.pat.nhs.uk/our-hospitals/the-royal-oldham-hospital/"
    },
    {
      "type": "wikipedia",
      "value": "https://en.wikipedia.org/wiki/Royal_Oldham_Hospital"
    }
  ],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "EU",
        "continent_name": "Europe",
        "country_code": "GB",
        "country_name": "United Kingdom",
        "country_subdivision_code": "ENG",
        "country_subdivision_name": "England",
        "lat": 53.54051,
        "lng": -2.1183,
        "name": "Oldham"
      },
      "geonames_id": 2641022
    }
  ],
  "names": [
    {
      "lang": "en",
      "types": [
        "alias"
      ],
      "value": "Oldham and District General Hospital"
    },
    {
      "lang": "en",
      "types": [
        "ror_display",
        "label"
      ],
      "value": "Royal Oldham Hospital"
    }
  ],
  "relationships": [
    {
      "label": "Northern Care Alliance NHS Foundation Trust",
      "type": "parent",
      "id": "https://ror.org/01nqeyn25"
    }
  ],
  "status": "active",
  "types": [
    "healthcare"
  ]
}

=== ror-community/ror-records/v2.9/00e348047.json
{
  "admin": {
    "created": {
      "date": "2026-03-24",
      "schema_version": "2.1"
    },
    "last_modified": {
      "date": "2026-06-23",
      "schema_version": "2.1"
    }
  },
  "domains": [],
  "established": null,
  "external_ids": [],
  "id": "https://ror.org/00e348047",
  "links": [],
  "locations": [
    {
      "geonames_details": {
        "continent_code": "AS",
        "continent_name": "Asia",
        "country_code": "JP",
        "country_name": "Japan",
        "country_subdivision_code": "13",
        "country_subdivision_name": "Tokyo",
        "lat": 35.68449,
        "lng": 139.75056,
        "name": "Chiyoda City"
      },
      "geonames_id": 11749713
    }
  ],
  "names": [
    {
      "lang": null,
      "types": [
        "alias"
      ],
      "value": "ID Pharma"
    },
    {
      "lang": null,
      "types": [
        "label"
      ],
      "value": "ID Pharma Co., Ltd."
    },
    {
      "lang": null,
      "types": [
        "label",
        "ror_display"
      ],
      "value": "ID Pharma Co., Ltd. (Japan)"
    },
    {
      "lang": "ja",
      "types": [
        "label"
      ],
      "value": "株式会社IDファーマ"
    }
  ],
  "relationships": [
    {
      "label": "ID Pharma (Japan)",
      "type": "successor",
      "id": "https://ror.org/05yk8hs36"
    }
  ],
  "status": "withdrawn",
  "types": [
    "company"
  ]
}
